replicaCount: 2

image:
  tag: "1.27-alpine"

ingress:
  enabled: true
  hosts:
    - host: staging.app.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 200m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4

env:
  - name: APP_ENV
    value: staging
  - name: DEBUG
    value: "false"